import { anyApi } from "convex/server";

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * This object is automatically generated by Convex and manual changes will be overwritten.
 */
export const api = anyApi;
