import { GenericApi } from "convex/server";
import type * as catalog from "../catalog";
import type * as lists from "../lists";
import type * as tests from "../tests";

/**
 * A type representing your app's public Convex API.
 *
 * This type is automatically generated by Convex and manual changes will be overwritten.
 */
export declare const api: GenericApi<
  {
    catalog: typeof catalog;
    lists: typeof lists;
    tests: typeof tests;
  }
>;
